import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/Footer";
import Providers from "@/components/context/Provider";
import AuthWrapper from "@/wrapper/authWrapper";
import ProtectedPageWrapper from "@/wrapper/ProtectedPageWrapper";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DropDoko - Your Digital Doko",
  description: "Generated by create next app",
  icons: {
    icon: "./favi.ico",
  },
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
        <Navbar/>
        <ProtectedPageWrapper>{children}</ProtectedPageWrapper>
        </Providers>
        <Footer/>
      </body>
    </html>
  );
}
